const sampleData = [
  {
    artist: 'dejaview',
    songName: 'just for the weekend [redo]',
    releaseDate: 'July 1, 2022',
    genre: 'rnb remix',
    key: 'f#m',
    bpm: 113,
    daw: 'ableton',
    description: 'A remix of SZA - "The Weekend". Featured on Soulection Radio #558',
    songURL: 'https://wlcwstpeuowhoknayute.supabase.co/storage/v1/object/public/Music/e9352a84-50a7-465e-9159-7eac28226ca9.mp3',
    imageURL: 'https://wlcwstpeuowhoknayute.supabase.co/storage/v1/object/public/SongArt/7ee32c84-dcff-4010-bd14-9ca014e3bd76.image',
  },
  {
    artist: 'dejaview',
    songName: 'my lady, my baby',
    releaseDate: 'February 16, 2023',
    genre: 'rnb remix',
    key: 'ebm',
    bpm: 80,
    daw: 'ableton',
    description: 'A remix of Wale ft. Miguel - "Lotus Flower Bomb"',
    songURL: 'https://wlcwstpeuowhoknayute.supabase.co/storage/v1/object/public/Music/9e8a35e8-6156-4658-b4dd-0077382d9207.mp3',
    imageURL: 'https://wlcwstpeuowhoknayute.supabase.co/storage/v1/object/public/SongArt/11536df7-c823-415b-9995-3cd171f242ea.image',
  },
  {
    artist: 'dejaview',
    songName: 'Will I See U At The Show Tonight?',
    releaseDate: 'July 3, 2020',
    genre: 'Hip Hop remix',
    key: 'am',
    bpm: 123,
    daw: 'ableton',
    description: 'A remix of Drake ft. Giveon - "Chicago Freestyle"',
    songURL: 'https://wlcwstpeuowhoknayute.supabase.co/storage/v1/object/public/Music/ca17339a-6e51-4e10-9337-07c9914756d3.mp3',
    imageURL: 'https://wlcwstpeuowhoknayute.supabase.co/storage/v1/object/public/SongArt/e683ff27-5e8a-4261-87b0-67e4f45262f6.image',
  },
  {
    artist: 'dejaview',
    songName: 'big sur [beat]',
    releaseDate: 'unreleased',
    genre: 'beat',
    key: 'g#maj',
    bpm: '95',
    daw: 'ableton',
    description: 'Sampled an old soul sample a few months ago. Still needs a bass',
    songURL: '',
    imageURL: '',
  },
];

export default sampleData;
